### ISSUE TITLE
Remote: refSpec HEAD did not resolve to a tree

### ISSUE THREAD

**Issue by jlanio** [locationtech/geogig#193]
After starting a remote repository with:
`geogig --repo "postgresql://localhost: 5432/geogig/master/imovel?user=postgres&password=admin" init`

And configure it with geoserver, making it available through the url:
`http://localhost:8080/geoserver/geogig/repos/imovel`

I'm having trouble starting work.
After performing the clone with:
`geogig clone http://localhost:8080/geoserver/geogig/repos/imovel imovel
`
I proceed to add the shape with:
`geogig shp import outside_de.shp`
```
Importing from shapefile outside_de.shp
0%
Importing fora_de (1/1) ...
1%
1 features inserted in 1,477 s
Building final tree ...
1 features tree built in 26.45 ms
100%
Out_de.shp imported successfully.
```

**But the problem arises when you add:**
`geogig add`
```
Counting unstaged elements...2
Staging changes...
refSpec HEAD did not resolve to a tree
```
-----
I have re-read the documentation countless times but I have not succeeded in finding my mistake. Could someone give me a light?

**Comment by gjsa73** [comment]
Same issue using geogig 1.3 to add into a newly init PostgreSQL repo:
``
geogig --repo %LG% add
``
```
Counting unstaged elements...2
Staging changes...
refSpec HEAD did not resolve to a tree
```

**Comment by DBlasby** [comment]
I havent seen that problem - I've imported a lot of data into geogig in 1.2 and 1.3.  Could you give more details?

**Comment by gjsa73** [comment]
I'm using PostgreSQL 10 and Geoserver 2.12
The repo that triggered the error was created using the geogig plugin in Geoserver 2.12 and it was reinitialised from the CLI before adding importing a shapefile.

I just created a new empty repo in the PG10 DB, from the command line and also from the geoserver extension and the import and add was successful in both cases.

So it may be something to do with the sequence of reinitialising an empty repo, or it may be a hard to reproduce error because I have 1.2.x geogig jars in geoserver and using 1.3 CLI to do the add.
