### ISSUE TITLE
Bug geogig 1.2.0 and PostgreSQL 10

### ISSUE THREAD

**Issue by dinizime** [locationtech/geogig#451]
I am having trouble while using Geogig version 1.2.0 and PostgresSQL 10.4 (version format error). Any ideas?

![image](https://user-images.githubusercontent.com/10109704/43861484-5df1dba4-9b2d-11e8-8b64-69a3f1ea3f69.png)

**Comment by emerkle826** [comment]
@dinizime This issue was fixed not long ago (https://github.com/locationtech/geogig/pull/426), however the fix has not made it into an official release as of yet (no more 1.2 releases are planned, and 1.3 has not been released yet at all). In order to use PostgreSQL 10 with GeoGig, you will have to build from the latest `1.2.x` branch or the latest `master` branch (1.3.x).

**Comment by groldan** [comment]
Closing, already answered.
