### ISSUE TITLE
Spatialite Support

### ISSUE THREAD

**Issue by Melegy90** [locationtech/geogig#490]
We can't seem to find any support for Spatialite with version 1.2 even though it is mentioned in the homepage of the GeoGig project that it is supported. Has Spatialite support been removed?

**Comment by groldan** [comment]
Hi there.
There seems to be a long-standing mismatch in the home page. Spatialite support was dropped in 2015 as of commit e9dcc0140477cd2d89f956c6f2071617eed70cea due to native libraries requirements (GEOS/proj). Moreover, this is probably more an issue of supporting any geotools datastore.
Problem with that is that GT is not very good at advertising how a feature id is composed (i.e. especially for RDBMS' where the fid could be a composite key), so importing is easy but exporting quite difficult.
If you're up for some coding, I think the proper place for this kind of external format support is a separate plugin. We could resurrect the geogig-plugins repository[1], probably under the geogig github organization rather than bounlessgeo so that it's owned by the community.

[1] https://github.com/boundlessgeo/geogig-plugins

**Comment by groldan** [comment]
Closing due to lack of feedback
